### PR TITLE
Added option to disable mootools

### PR DESCRIPTION
**Pull request by thexmanxyz**
As the title suggests, I added the functionality to disable the mootools loading if necessary. This might be a useful parameter to configure for plugin users.

### CODE REVIEW

**Comment by fevangelou** [comment]
You're reading the code wrong. We're not using Mootools. Mootools is only enforced to load in Joomla 1.5 and 2.5 in order for jQuery not to conflict with Mootools code.

**Comment by thexmanxyz** [comment]
@fevangelou This is not true this was already outlined in a previous issue. You enforce MooTools on all Version `>=1.5` and `>=2.5` but not if version is `>=4.0`. This is exactly what this code does. 

```
if (version_compare(JVERSION, '4', 'ge')) {
    // Do nothing
} elseif (version_compare(JVERSION, '2.5.0', 'ge')) {
    JHTML::_('behavior.framework');
} else {
    JHTML::_('behavior.mootools');
}
```

**Comment by fevangelou** [comment]
Cause Mootools is still part of Joomla 3.x. And other plugins may load Mootools. We don't want things to conflict. If this was my mistake, there would be not check for J4 now wouldn't it?

**Comment by fevangelou** [comment]
As a sidenote, if you don't wish to load Mootools for your site, it's a one-liner to get rid of it in your template.

**Comment by thexmanxyz** [comment]
@fevangelou Yes MooTools is part of Joomla 3.x but that was not my point and that doesn't even matter. There are circumstances where there is no necessity to load MooTools on J3. E.g. in case of G5 and TBH IDK where it would be necessary to load MooTools on J3 at all. But nevermind. Loading useless JS code on a web page which doesn't need it is bad practise and this PR counters this behaviour. It's your decision to leave it the way it is. It was just a suggestion. I'm off discussing in a circle if there is no interest in understanding the particular problem.

**Pull request closed without merging**
